# Site
name: "MySecondLife"
title: "Logs of my journey to freelance UX Design"
description: "Logs of my journey to freelance UX Design"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mysecondlife
google_analytics: 'UA-151336784-1'
disqus: 'mysecondlife-sum'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Sumit:
    name: Sumit
    display_name: Sumit
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: sumit4palz@gmail.com
    web: https://www.sumgup.github.com/mysecondlife
    twitter: https://twitter.com/sumit4palz
    description: "Giving human aspect to every thing I touch"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
